version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: siscat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: siscat_db
      POSTGRES_USER: siscat_user
      POSTGRES_PASSWORD: siscat_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - siscat-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U siscat_user -d siscat_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: siscat-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@siscat.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - siscat-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  siscat-network:
    driver: bridge
