package com.app.catastro.model.catastro;


@lombok.Data

public class fichaCatrastroMovil {
	
	 String codempre;
     String codsuc;//
     String distrito;
     int codcliente;
     String inspector;
     String trabajador;
     String cantidad;
     String ultimo_registro;
     String idficha;
     /*String codsector_new;
     String codmza_new;
     String nrolote_new;
     String nrosublote_new;
     String propietario;*/
     String direccion;
     String fechareg;
     String latitud;
     String longitud;
     String fecha_filtro;
     
     String codsector;
     String fechaini;
     String fechafin;
     String id;
     String info;
     String resu;
     /*String fotofachada;
     String fotocajaagua;
     String fotocajadesague;*/
     String fotodetalle4;
     String fotodetalle5;
     String codbrigada;
    // String objectID;
    
     
     
    
     String codprov;
   //  String codcatastral;
    // String calle;
    // String fecha;
   //  String tipoacccomercial;
   //  String observacion;
     
     
     String codemp;
     //String cuadra;
     String nromunic;
     String mzamunic;
     String ltemunic;
     String numero_dir;
     String referencia;
     String referencia_new;
     String direccion_new;
     String direccion_campo;
     String nrocalle;
   //  String urbanizacion;
   //  String tipoconstruccion;
    // String nropisos;
     String tiposervicio;
     String tiposervicio_new;
     String tipoaba;
   //  String piscina;
     String codalmacenaje;
   //  String tipousuario;
     String datos_correctos;
     String propietario_new;
    // String dni;
     String habitada;
    // String habitantes;
    // String tiporesponsable;
     String celular;
    // String nrocontrato;
     String codreservorio;
     String codsectorabast;
     String catetar;
     String catetar_new;
     String unidusotmp;
     String actividad;
    // String razonsocial;
     String situacionconex_a;
     String pavconagu_a;
    // String vereda_a;
     String coddiametro_a;
     String  coddiametro_anew;
     String tipomaterial_a;
     String tipoingreso;
     String concajaagua;
     String tipocaja_a;
     String loccaja_a;
     //String estadocaja_a;
     String contapaagua;
     String tipotapa_a;
     String esttapa_a;
     String llavemed;
     String posicionmed;
     //String tipocorte_a;
     String tipocerrado;
     String tipofugas_a;
     String tipocajaobserv;
     //String tienemedidor;
     String nromed;
     String nromed_new;
     String modelomed;
     //String anio;
     String lecturaultima;
     //String fechainstalacion;
     String marcamed;
     String coddiametro_m;
     //String lectura;
     //String tipofacturacion;
     //String tipolectura;
     String estadomed;
     //String medidoroperativo;
     String situacionconex_d;
     String coddiametro_d;
     String tipomaterial_d;
     String concajadesague;
     String tipocaja_d;
     String loccaja_d;
     //String estadocaja_d;
     String contapadesague;
     //String tipotapa_d;
     String esttapa_d;
     String tipofugas_d;
     //String horasxdia;
     /*String diasxsemana;
     String presionagu;
     String nrolavatorios;
     String estadolavatorios;
     String nrolavadoras;
     String estadolavadoras;*/
     //String nrowater;
    /* String estadowater;
     //String nroduchas;
     String estadoduchas;
     //String nrourinarios;
     String estadourinarios;
     //String nrogrifos;
     String estadogrifos;
     String nropiscina;
     String estadopiscina;
     //String nrotanquecisterna;
     String estadotanquecisterna;
     //String nrotanqueelevado;
     String estadotanqueelevado;
     String fichaincompleta;
     String encuestador;
     String usermodificador;
     String fechamodificacion;*/
     String creador;
     String nrocatastro;
     String estareg;
     String fecha_visita;
     String hora_visita;
     String gestor;
     String estadoservicio;
     String codmza;
     String nrolote;
     String nrosublote;
     String tipomaterialconst;
     String tipopredio;
     String email;
     String suministroluz;
     String tipoaccesoriosconex_a;
     String estconexion_a;
     String tipoaccesoriosnoreglamentados_a;
     String tipomodelocajaconex_a;
     String tipomed;
     String tipotapondeo_d;
     String pavconagu_d;
     String vereda_d;
     String fugasdesague;
     String tipomodelocajaconex_d;
     String sospechosovma;
     String medidalotefrente;
     String medidaejeagua;
     String medidaejedesague;
     
     //ultimo
     
      String region;
      String sucursal;
      String sector;
      String mzna;
      String lote;
      String sublote;
      int suministro;
      String calle;
      String cuadra;
      String nromuni;
      String mzmuni;
      String ltmuni;
      String urbanizacion;
      String tipoconstruccion;
      String nropisos;
      String tiposervicio_campo;
      String abastecimiento;
      String piscina;
      String almacenaje;
      String tipousuario;
      String apellidosnombre_campo;
      String dni;
      int habitantes;
      String tiporesponsable;
      String telefono;
      String nrocontrato;
      String reservorio;
      String sectabastecimiento;
      String categoriascampo;
      String actividades;
      String razonsocial;
      String estservicio_a;
      String pavimento_a;
      String vereda_a;
      String diametrocampo_a;
      String materialtubo_a;
      String tipoingreso_a;
      String caja_a;
      String materialcaja_a;
      String localizacion_a;
      String estadocaja_a;
      String tapa_a;
      String materialtapa_a;
      String estadotapa_a;
      String llaves;
      String posicionmedidor;
      String tipocorte_a;
      String razoncorte;
      String fugas_a;
      String tipocajaobserv_a;
      String tienemedidor;
      String medidorcampo;
      String modelomedidor;
      String anio;
      int lecturamedidor;
      String fechainstalacion;
      String marcamedidor;
      String diametromedidor;
      String lectura;
      String tipofacturacion;
      String tipolectura;
      String estadomedidor;
      String medidoroperativo;
      String estservicio_d;
      String diametrocampo_d;
      String materialtubo_d;
      String caja_d;
      String materialcaja_d;
      String localizacion_d;
      String estadocaja_d;
      String tapa_d;
      String tipotapa_d;
      String estadotapa_d;
      String fugas_d;
      String horasxdia;
      String diasxsemana;
      String presionagu;
      int nrolavatorios;
      String estadolavatorios;
      int nrolavadoras;
      String estadolavadoras;
      int nrowater;
      String estadowater;
      int nroduchas;
      String estadoduchas;
      int nrourinarios;
      String estadourinarios;
      int nrogrifos;
      String estadogrifos;
      int nropiscina;
      String estadopiscina;
      int nrotanquecisterna;
      String estadotanquecisterna;
      int nrotanqueelevado;
      String estadotanqueelevado;
      String observacion;
      String fichaincompleta;
      String tipoacccomercial;
      String encuestador;
      String fecencuestador;
      String calidad;
      String feccalidad;
      String supervisor;
      String fecsupervisor;
      String supervision;
      String fecsupervision;
      int objectID;
      String posicionx;
      String posiciony;
      String usermodificador;
      String fechamodificacion;
      String codcatastral;
      String coddist;
      String codsector_new;
      String codmza_new;
      String nrolote_new;
      String nrosublote_new;
      String propietario;
      String fecha;
      String fotofachada;
      String fotocajaagua;
      String fotocajadesague;
      String usersys;
      

      int fichaaprobada;
     // fechaaprobacion;
      String codcalle;
      String codurbaso;
  
}



