export const listaDataExportHeaders = [
    "ID Ficha", "Empresa", "Sucursal", "Provincia", "Sector", "Manzana", "Lote", "Sublote", "Cliente", "Nro Catastro",
    "Cuadra", "Nro Municipal", "Mz Municipal", "Lt Municipal", "Número Dirección", "Referencia", "Referencia Nueva", "Dirección Nueva", "Dirección Campo", "Dirección", "Nro Calle", "Urbanización",
    "Tipo Construcción", "Nro Pisos", "Tipo Material Const", "Tipo Predio",
    "Tipo Servicio", "Tipo Servicio Nuevo", "Tipo ABA", "Piscina", "Código Almacenaje", "Tipo Usuario", "Estado Servicio",
    "Propietario", "Propietario Nuevo", "DNI", "Habitada", "Habitantes", "Tipo Responsable", "Celular", "Nro Contrato", "Email", "Datos Correctos",
    "Código Reservorio", "Sector Abastecimiento", "Catetar", "Catetar Nuevo", "Unidad Uso Temporal", "Actividad", "Razón Social",
    "Situación Conexión Agua", "Pavimento Conexión Agua", "Vereda Agua", "Código Diámetro Agua", "Código Diámetro Agua Nuevo", "Tipo Material Agua", "Tipo Ingreso", "Con Caja Agua", "Tipo Caja Agua", "Localización Caja Agua", "Estado Caja Agua", "Con Tapa Agua", "Tipo Tapa Agua", "Estado Tapa Agua", "Llave Medidor", "Posición Medidor", "Tipo Corte Agua", "Tipo Cerrado", "Tipo Fugas Agua", "Tipo Caja Observación", "Tipo Accesorios Conexión Agua", "Estado Conexión Agua", "Tipo Accesorios No Reglamentados Agua", "Tipo Modelo Caja Conexión Agua",
    "Tiene Medidor", "Nro Medidor", "Nro Medidor Nuevo", "Modelo Medidor", "Año", "Lectura Última", "Fecha Instalación", "Marca Medidor", "Código Diámetro Medidor", "Lectura", "Tipo Facturación", "Tipo Lectura", "Estado Medidor", "Medidor Operativo", "Tipo Medidor",
    "Situación Conexión Desagüe", "Código Diámetro Desagüe", "Tipo Material Desagüe", "Con Caja Desagüe", "Tipo Caja Desagüe", "Localización Caja Desagüe", "Estado Caja Desagüe", "Con Tapa Desagüe", "Tipo Tapa Desagüe", "Estado Tapa Desagüe", "Tipo Fugas Desagüe", "Tipo Tapón Deo Desagüe", "Pavimento Conexión Agua Desagüe", "Vereda Desagüe", "Fugas Desagüe", "Tipo Modelo Caja Conexión Desagüe",
    "Horas por Día", "Días por Semana", "Presión Agua", "Suministro Luz",
    "Nro Lavatorios", "Estado Lavatorios", "Nro Lavadoras", "Estado Lavadoras", "Nro Water", "Estado Water", "Nro Duchas", "Estado Duchas", "Nro Urinarios", "Estado Urinarios", "Nro Grifos", "Estado Grifos", "Nro Piscina", "Estado Piscina", "Nro Tanque Cisterna", "Estado Tanque Cisterna", "Nro Tanque Elevado", "Estado Tanque Elevado",
    "Observación", "Observaciones", "Ficha Incompleta", "Tipo Acción Comercial", "Sospechoso VMA",
    "Medida Lote Frente", "Medida Eje Agua", "Medida Eje Desagüe",
    "Latitud", "Longitud",
    "Foto Fachada", "Foto Caja Agua", "Foto Caja Desagüe", "Foto Detalle 4", "Foto Detalle 5",
    "Fecha Visita", "Hora Visita",
    "Gestor", "Inspector", "Código Inspector", "Encuestador",
    "Código Brigada",
    "Usuario Modificador", "Fecha Modificación", "Creador", "Fecha Registro", "Fecha Registro",
    "Ficha Aprobada", "Fecha Aprobación", "Estado Ficha", "Fecha Entrega Ficha", "Est Duplicado", "Estareg",
    "Código Manzana", "Nro Lote", "Nro Sublote"
]

export const listaDataExportFieldMapping = [
    "idficha", "codemp", "codsuc", "codprov", "codsector_new", "codmza_new", "nrolote_new", "nrosublote_new", "codcliente", "nrocatastro",
    "cuadra", "nromunic", "mzamunic", "ltemunic", "numero_dir", "referencia", "referencia_new", "direccion_new", "direccion_campo", "direccion", "nrocalle", "urbanizacion",
    "tipoconstruccion", "nropisos", "tipomaterialconst", "tipopredio",
    "tiposervicio", "tiposervicio_new", "tipoaba", "piscina", "codalmacenaje", "tipousuario", "estadoservicio",
    "propietario", "propietario_new", "dni", "habitada", "habitantes", "tiporesponsable", "celular", "nrocontrato", "email", "datos_correctos",
    "codreservorio", "codsectorabast", "catetar", "catetar_new", "unidusotmp", "actividad", "razonsocial",
    "situacionconex_a", "pavconagu_a", "vereda_a", "coddiametro_a", "coddiametro_anew", "tipomaterial_a", "tipoingreso", "concajaagua", "tipocaja_a", "loccaja_a", "estadocaja_a", "contapaagua", "tipotapa_a", "esttapa_a", "llavemed", "posicionmed", "tipocorte_a", "tipocerrado", "tipofugas_a", "tipocajaobserv", "tipoaccesoriosconex_a", "estconexion_a", "tipoaccesoriosnoreglamentados_a", "tipomodelocajaconex_a",
    "tienemedidor", "nromed", "nromed_new", "modelomed", "anio", "lecturaultima", "fechainstalacion", "marcamed", "coddiametro_m", "lectura", "tipofacturacion", "tipolectura", "estadomed", "medidoroperativo", "tipomed",
    "situacionconex_d", "coddiametro_d", "tipomaterial_d", "concajadesague", "tipocaja_d", "loccaja_d", "estadocaja_d", "contapadesague", "tipotapa_d", "esttapa_d", "tipofugas_d", "tipotapondeo_d", "pavconagu_d", "vereda_d", "fugasdesague", "tipomodelocajaconex_d",
    "horasxdia", "diasxsemana", "presionagu", "suministroluz",
    "nrolavatorios", "estadolavatorios", "nrolavadoras", "estadolavadoras", "nrowater", "estadowater", "nroduchas", "estadoduchas", "nrourinarios", "estadourinarios", "nrogrifos", "estadogrifos", "nropiscina", "estadopiscina", "nrotanquecisterna", "estadotanquecisterna", "nrotanqueelevado", "estadotanqueelevado",
    "observacion", "obs", "fichaincompleta", "tipoacccomercial", "sospechosovma",
    "medidalotefrente", "medidaejeagua", "medidaejedesague",
    "latitud", "longitud",
    "fotofachada", "fotocajaagua", "fotocajadesague", "fotodetalle4", "fotodetalle5",
    "fecha_visita", "hora_visita",
    "gestor", "inspector", "codinspector", "encuestador",
    "codbrigada",
    "usermodificador", "fechamodificacion", "creador", "fechareg", "fecharegistro",
    "fichaaprobada", "fechaaprobacion", "estadoficha", "fechaentregaficha", "est_duplicado", "estareg",
    "codmza", "nrolote", "nrosublote"
]