export interface Cliente {
    codemp: string;
    codsuc: string;
    codcliente: number;
    codiusua?: string;
    codsector: string;
    codcalle: number;
    nrocalle?: string;
    codmza?: string;
    codcatastral: string;
    referencia?: string;
    codurbaso?: string;
    tiposervicio?: string;
    tipousuario: string;
    tiporesponsable?: string;
    distrecibos?: string;
    nrocontrato?: number;
    inquilino?: string;
    propietario: string;
    telefono?: string;
    codcalledircor?: number;
    nrocalledircor?: string;
    unidaddom?: number;
    unidadcom?: number;
    unidadind?: number;
    unidadsoc?: number;
    unidadest?: number;
    estadoregistro: number;
    sinmora: number;
    flagnuevousu?: string;
    codentpub?: string;
    ruc?: string;
    catetar?: string;
    codrutadistribucion?: number;
    variasunidadesuso: number;
    fechaprorroga?: string;
    altocon: number;
    estadoservicio?: string;
    tipocerrado?: string;
    estareg: number;
    creador?: string;
    fechareg?: string;
    nrolote?: string;
    codciclo?: string;
    codrutalectura?: number;
    nroordenrutalect?: number;
    nroordenrutadist?: number;
    fechacorte?: string;
    fechareapertura?: string;
    precorte: number;
    direcc?: string;
    nrosublote?: string;
    sinmoraotrosser: number;
    sinigvotrosser: number;
    actividad?: string;
    nropresupuesto?: number;
    redondeo?: number;
    dni?: string;
    tipodocumento?: string;
    nrodocumento?: string;
    codtipotramiteingreso?: string;
    nrotramiteingreso?: string;
    impedimentocorte: number;
    conexionhastacaja: number;
    conexiontemporal: number;
    fechalimitetemporal?: string;
    seguimientocomercial: number;
    obs?: string;
    fechaanulacion?: string;
    codsucdircor?: string;
    desaguexderivacion: number;
    codclientedircor?: number;
    estadosis?: string;
    codgis?: string;
    fechacontrato?: string;
    usuario?: number;
    clave?: string;
    renuevcont?: number;
    retenidoxpprn: number;
    porcdescarfuenpropia?: number;
    fuentepropia: number;
    judicializado: number;
    infocorp: number;
    tipopromediofp?: string;
    consumoxfuenpropia?: number;
    coddpto?: string;
    codprov?: string;
    coddist?: string;
    codclienteund?: number;
    und: number;
    sec_new?: string;
    mzn_new?: string;
    lote_new?: string;
    con_new?: string;
    ruta_new?: number;
    orden_new?: number;
    codproyectofon?: string;
    email?: string;
    codciiu?: string;
    inactividad?: number;
    estadosaldo?: string;
    codmzaab?: string;
    fichaactualizada: number;
    fechacortelimiteasol?: string;
    retenidoasolictud: number;
    feciniactividad?: string;
    codcentropobla?: string;
    enlitigio: number;
    contratofirmado?: number;
    explitigio?: string;
    fechainiciofact?: string;
    puntual: number;
    codmotivocorte?: string;
    codmotivoreapertura?: string;
    motivo_no_ejecuto: number;
    ejecuto_corte: number;
    deuda?: number;
    mesesdeuda?: number;
    deuda_interes?: number;
    diapa?: string;
    codentpub_orecip?: string;
    nombrecomercial?: string;
    noconsiderar: number;
    unidadcom2?: number;
    nrocontrato_sici?: string;
    codinspector?: string;
    codbrigada?: string;
    fechaasignacion?: string;
    inspector?: string;
}

export interface ClienteDto {
    codemp: string;
    codsuc: string;
    codcliente: number;
    codiusua?: string;
    codsector: string;
    codcalle: number;
    nrocalle?: string;
    codmza?: string;
    codcatastral: string;
    referencia?: string;
    codurbaso?: string;
    tiposervicio?: string;
    tipousuario: string;
    tiporesponsable?: string;
    distrecibos?: string;
    nrocontrato?: number;
    inquilino?: string;
    propietario: string;
    telefono?: string;
    codcalledircor?: number;
    nrocalledircor?: string;
    unidaddom?: number;
    unidadcom?: number;
    unidadind?: number;
    unidadsoc?: number;
    unidadest?: number;
    estadoregistro: number;
    sinmora: number;
    flagnuevousu?: string;
    codentpub?: string;
    ruc?: string;
    catetar?: string;
    codrutadistribucion?: number;
    variasunidadesuso: number;
    fechaprorroga?: string;
    altocon: number;
    estadoservicio?: string;
    tipocerrado?: string;
    estareg: number;
    creador?: string;
    fechareg?: string;
    nrolote?: string;
    codciclo?: string;
    codrutalectura?: number;
    nroordenrutalect?: number;
    nroordenrutadist?: number;
    fechacorte?: string;
    fechareapertura?: string;
    precorte: number;
    direcc?: string;
    nrosublote?: string;
    sinmoraotrosser: number;
    sinigvotrosser: number;
    actividad?: string;
    nropresupuesto?: number;
    redondeo?: number;
    dni?: string;
    tipodocumento?: string;
    nrodocumento?: string;
    codtipotramiteingreso?: string;
    nrotramiteingreso?: string;
    impedimentocorte: number;
    conexionhastacaja: number;
    conexiontemporal: number;
    fechalimitetemporal?: string;
    seguimientocomercial: number;
    obs?: string;
    fechaanulacion?: string;
    codsucdircor?: string;
    desaguexderivacion: number;
    codclientedircor?: number;
    estadosis?: string;
    codgis?: string;
    fechacontrato?: string;
    usuario?: number;
    clave?: string;
    renuevcont?: number;
    retenidoxpprn: number;
    porcdescarfuenpropia?: number;
    fuentepropia: number;
    judicializado: number;
    infocorp: number;
    tipopromediofp?: string;
    consumoxfuenpropia?: number;
    coddpto?: string;
    codprov?: string;
    coddist?: string;
    codclienteund?: number;
    und: number;
    sec_new?: string;
    mzn_new?: string;
    lote_new?: string;
    con_new?: string;
    ruta_new?: number;
    orden_new?: number;
    codproyectofon?: string;
    email?: string;
    codciiu?: string;
    inactividad?: number;
    estadosaldo?: string;
    codmzaab?: string;
    fichaactualizada: number;
    fechacortelimiteasol?: string;
    retenidoasolictud: number;
    feciniactividad?: string;
    codcentropobla?: string;
    enlitigio: number;
    contratofirmado?: number;
    explitigio?: string;
    fechainiciofact?: string;
    puntual: number;
    codmotivocorte?: string;
    codmotivoreapertura?: string;
    motivo_no_ejecuto: number;
    ejecuto_corte: number;
    deuda?: number;
    mesesdeuda?: number;
    deuda_interes?: number;
    diapa?: string;
    codentpub_orecip?: string;
    nombrecomercial?: string;
    noconsiderar: number;
    unidadcom2?: number;
    nrocontrato_sici?: string;
    codinspector?: string;
    codbrigada?: string;
    fechaasignacion?: string;
    inspector?: string;
}

// Request para crear/actualizar cliente
export interface ClienteRequest {
    codemp: string;
    codsuc: string;
    codcliente?: number;
    codiusua?: string;
    codsector: string;
    codcalle: number;
    nrocalle?: string;
    codmza?: string;
    codcatastral: string;
    referencia?: string;
    codurbaso?: string;
    tiposervicio?: string;
    tipousuario: string;
    tiporesponsable?: string;
    distrecibos?: string;
    nrocontrato?: number;
    inquilino?: string;
    propietario: string;
    telefono?: string;
    codcalledircor?: number;
    nrocalledircor?: string;
    unidaddom?: number;
    unidadcom?: number;
    unidadind?: number;
    unidadsoc?: number;
    unidadest?: number;
    estadoregistro: number;
    sinmora: number;
    codentpub?: string;
    ruc?: string;
    catetar?: string;
    codrutadistribucion?: number;
    variasunidadesuso: number;
    fechaprorroga?: string;
    altocon: number;
    estadoservicio?: string;
    tipocerrado?: string;
    nrolote?: string;
    codciclo?: string;
    codrutalectura?: number;
    nroordenrutalect?: number;
    nroordenrutadist?: number;
    precorte: number;
    direcc?: string;
    nrosublote?: string;
    sinmoraotrosser: number;
    sinigvotrosser: number;
    actividad?: string;
    nropresupuesto?: number;
    redondeo?: number;
    dni?: string;
    tipodocumento?: string;
    nrodocumento?: string;
    codtipotramiteingreso?: string;
    nrotramiteingreso?: string;
    impedimentocorte: number;
    conexionhastacaja: number;
    conexiontemporal: number;
    fechalimitetemporal?: string;
    seguimientocomercial: number;
    obs?: string;
    desaguexderivacion: number;
    codclientedircor?: number;
    estadosis?: string;
    codgis?: string;
    fechacontrato?: string;
    usuario?: number;
    clave?: string;
    renuevcont?: number;
    retenidoxpprn: number;
    porcdescarfuenpropia?: number;
    fuentepropia: number;
    judicializado: number;
    infocorp: number;
    tipopromediofp?: string;
    consumoxfuenpropia?: number;
    coddpto?: string;
    codprov?: string;
    coddist?: string;
    codclienteund?: number;
    und: number;
    sec_new?: string;
    mzn_new?: string;
    lote_new?: string;
    con_new?: string;
    ruta_new?: number;
    orden_new?: number;
    codproyectofon?: string;
    email?: string;
    codciiu?: string;
    inactividad?: number;
    estadosaldo?: string;
    codmzaab?: string;
    fichaactualizada: number;
    fechacortelimiteasol?: string;
    retenidoasolictud: number;
    feciniactividad?: string;
    codcentropobla?: string;
    enlitigio: number;
    contratofirmado?: number;
    explitigio?: string;
    fechainiciofact?: string;
    puntual: number;
    codmotivocorte?: string;
    codmotivoreapertura?: string;
    motivo_no_ejecuto: number;
    ejecuto_corte: number;
    deuda?: number;
    mesesdeuda?: number;
    deuda_interes?: number;
    diapa?: string;
    codentpub_orecip?: string;
    nombrecomercial?: string;
    noconsiderar: number;
    unidadcom2?: number;
    nrocontrato_sici?: string;
    codinspector?: string;
    codbrigada?: string;
    fechaasignacion?: string;
    inspector?: string;
}

// Response de la API
export interface ClienteResponse {
    success: boolean;
    message: string;
    data: ClienteDto;
    timestamp: string;
}

export interface ClientesResponse {
    success: boolean;
    message: string;
    data: ClienteDto[];
    timestamp: string;
}

// Funciones de utilidad para clientes
export const isActive = (cliente: ClienteDto | null): boolean => {
    return cliente?.estareg === 1;
};

export const hasActiveService = (cliente: ClienteDto | null): boolean => {
    return cliente?.estadoservicio !== null && cliente?.estadoservicio !== '';
};

export const isInLitigation = (cliente: ClienteDto | null): boolean => {
    return cliente?.enlitigio === 1;
};

export const hasDebt = (cliente: ClienteDto | null): boolean => {
    return cliente?.deuda !== null && cliente?.deuda !== undefined && cliente?.deuda > 0;
};

export const getClienteFullName = (cliente: ClienteDto | null): string => {
    if (!cliente) return "Cliente";
    return cliente.propietario || "Sin nombre";
};

export const getClienteCode = (cliente: ClienteDto | null): string => {
    if (!cliente) return "";
    return `${cliente.codemp}-${cliente.codsuc}-${cliente.codcliente}`;
};

export const getClienteAddress = (cliente: ClienteDto | null): string => {
    if (!cliente) return "";
    const parts = [
        cliente.direcc,
        cliente.nrocalle,
        cliente.referencia
    ].filter(Boolean);
    return parts.join(", ");
};

export const getClienteCatastralCode = (cliente: ClienteDto | null): string => {
    if (!cliente) return "";
    return cliente.codcatastral || "";
};

export const isTemporaryConnection = (cliente: ClienteDto | null): boolean => {
    return cliente?.conexiontemporal === 1;
};

export const isPunctualPayer = (cliente: ClienteDto | null): boolean => {
    return cliente?.puntual === 1;
};

export const hasOwnSource = (cliente: ClienteDto | null): boolean => {
    return cliente?.fuentepropia === 1;
}; 